#!/usr/bin/env bash
# configure subdomains

show_information ()
{
  domain="$1"
  subdomain="$2"
  line=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
  echo "$subdomain $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
  if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
  then
    show_information "$1" "$subdomain"
  fi
done
