#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /custom_404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
