#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 509154-web-01 54.236.44.41 check
    server 509154-web-02 100.26.239.146 check
"
# Update packages
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4

# Install HAProxy
apt-get -y install haproxy
echo "$balancer" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy restart
