#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 509154-web-01 18.207.207.191:80 check
    server 509154-web-02 34.229.70.147:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade


# Install HAProxy
apt-get -y install haproxy
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
