#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
cd /etc/nginx/sites-enabled/ || exit;
rm default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart;

