#!/usr/bin/env bash
# advanced script

echo $$ >> /var/run/myscript.pid

trap "sudo rm -f /var/run/codingschoolscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/codingschoolscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT

while true
do
    echo "to infinity and beyond"
    sleep 2
done