#!/usr/bin/env bash
# setup application server for the server

echo "Updating Packages and Installing Requirements"

# Update Package Manager
apt-get update
apt-get install -y nginx
# Install pip
apt-get install -y python3-pip
# Install Flask, flask_cors, sqlalchemy Using PIP
pip install flask
pip install flask_cors
pip install sqlalchemy
# Install net-tools
apt install -y net-tools
# Install GUNICORN
apt-get install -y gunicorn
# Remove any current AIRBNB Repositoty
rm -rf AirBnB_clone_v*
# Clone My Repository
git clone https://github.com/A-Yehia19/AirBnB_clone_v2
git clone https://github.com/A-Yehia19/AirBnB_clone_v3
git clone https://github.com/mabakry/AirBnB_clone_v4
# Change Directory
cd AirBnB_clone_v2

# Define the path to the Nginx configuration file to be overwritten
NGINX_CONFIG="/etc/nginx/sites-enabled/default"

# Overwrite the Nginx configuration file with the provided configuration
tee "$NGINX_CONFIG" > /dev/null <<EOF
server {
    # Listen on port 80
    listen 80 default_server;
    listen [::]:80 default_server;

    # Use IP of server as domain name
    server_name 54.236.44.41;

    # Customize HTTP response header
    add_header  X-Served-By 509154-web-01;

    # Serve /airbnb-onepage/ route from AirBnB_clone_v2
    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # Serve /number_odd_or_even/ route on AirBnB_clone_v2
    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    # Serve API on AirBnB_clone_v3
    location /api {
        proxy_pass http://127.0.0.1:5002/api;
    }

    # Configure /2-hbnb route of AirBnB_clone_v4 as root location
    location / {
        proxy_pass http://127.0.0.1:5003/2-hbnb;
    }

    # Serve static content for AirBnB_clone_v4
    location /static {
        proxy_pass http://127.0.0.1:5003;
    }

    # 404 error page
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
systemctl restart nginx

echo "Done !!!!"